### ISSUE TITLE
Quick start does not work without setting ENV

### ISSUE THREAD

**Issue by aldeed** [Phoenix-Codeworx/phoenix-framework#30]
When you clone and then try to `bun start` or `bun dev`, you get:

```txt
================================
 Missing environment variables:
    JWT_SECRET: Secret key for JWT token
    MONGO_URI: MongoDB connection string
================================
```

For `JWT_SECRET`, we can add a `devDefault` with any value in the envalid config.

For `MONGO_URI`, I have a project I can find where I have the `dev` script set up to also start mongo using docker. If we copy that approach, it will be truly plug-n-play for getting started.

**Comment by brent-hoover** [comment]
@aldeed Yeah, I kept meaning to take the .env I had and copy it over to an .env.example but just kept forgetting.

BUt yeah, good idea to just establish dev defaults in the .env file. It turns out that bun auto-loads .env files automatically but I think it's still worth using envalid for env validation.

**Comment by aldeed** [comment]
> It turns out that bun auto-loads .env files automatically

Interesting, so the dotenv package can be removed?

**Comment by brent-hoover** [comment]
> Interesting, so the dotenv package can be removed?

I don't think so unless we just switched to just using process.env, because the envalid package still needs it to read dotenv (at least I think it does). I think having envalid validation is worth it to keep the package in.
